name: Build Java and Rust
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        java: [ "11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: ./gradlew build

      - name: Upload rust release build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cargo-build
          if-no-files-found: error
          path: datafusion-jni/target/release/libdatafusion_jni*
          retention-days: 3

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datafusion-java
          if-no-files-found: error
          path: ~/.m2/repository/io/github/datafusion-contrib/datafusion-java
          retention-days: 3
