name: Build
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  rust:
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cargo build
        run: ./gradlew cargoReleaseBuild

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: datafusion-jni-${{ matrix.os }}
          if-no-files-found: error
          path: "datafusion-jni/target/release/libdatafusion_jni.dylib"
          retention-days: 3

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: datafusion-jni-${{ matrix.os }}
          if-no-files-found: error
          path: "datafusion-jni/target/release/libdatafusion_jni.so"
          retention-days: 3

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: datafusion-jni-${{ matrix.os }}
          if-no-files-found: error
          path: "datafusion-jni\\target\\release\\libdatafusion_jni.dll"
          retention-days: 3

  java:
    needs:
      - rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Download ubuntu artifacts
        uses: actions/download-artifact@v3
        with:
          name: datafusion-jni-ubuntu-latest
          path: datafusion-jni/target/release

      #      - name: Download windows artifacts
      #        uses: actions/download-artifact@v3
      #        with:
      #          name: datafusion-jni-windows-latest
      #          path: datafusion-jni/target/release

      - name: Download macos artifacts
        uses: actions/download-artifact@v3
        with:
          name: datafusion-jni-macos-latest
          path: datafusion-jni/target/release

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datafusion-java
          if-no-files-found: error
          path: ~/.m2/repository/io/github/datafusion-contrib/datafusion-java
          retention-days: 3

      - name: Publish to Sonatype
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
